version: "3"
networks:
  default:
services:
  zookeeper:
    image: debezium/zookeeper:0.9.2.Final
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
  kafka:
    image: wurstmeister/kafka:2.12-2.1.1
    container_name: kafka
    hostname: kafka
    ports:
      - "9093:9093"
    links:
      - zookeeper
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092,DEV://:9093
      #creating listeners for internal access from docker and for development on localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,DEV://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,DEV:PLAINTEXT
  schema-registry:
    image: confluentinc/cp-schema-registry:5.4.0
    container_name: schema-registry
    hostname: schema-registry
    ports:
      - "8081:8081"
    links:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
      SCHEMA_REGISTRY_DEBUG: "true"
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS : PLAINTEXT://kafka:9092